
spring:
  main:
    banner-mode: off

  datasource:
    url: jdbc:postgresql://postgres:5432/
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:secret}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    properties.hibernate.format_sql: true
    hibernate:
      ddl-auto: update
